create SCHEMA IF NOT EXISTS TESTDB;

drop table IF EXISTS TESTDB.RESTAURANT CASCADE;

-- restaurant table --

create TABLE IF NOT EXISTS TESTDB.RESTAURANT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50),
    STAR_NUMBER INT DEFAULT 0
);